apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: frontend
  namespace: roboshop
  # these are replica set labels
  labels:
    component: frontend
    project: robosop
    tier: frontend
spec:
  replicas: 1
  selector:
    # these labesl are used to select pods
    matchLabels:
      component: frontend
      project: robosop
      tier: frontend
#POD definition
  template:
    metadata: 
      labels:
        component: frontend
        project: robosop
        tier: frontend
    spec:
      containers: 
      - name: nginx
        image: navomika18/frontend:v1
        imagePullPolicy: Always
        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    component: frontend
    project: robosop
    tier: frontend
  ports: 
    - protocol: TCP
      port: 80 # service port
      targetPort: 8080 # container port
