apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: rabbitmq
  namespace: roboshop
  # these are replica set labels
  labels:
    component: rabbitmq
    project: robosop
    tier: db
spec:
  replicas: 1
  selector:
    # these labesl are used to select pods
    matchLabels:
      component: rabbitmq
      project: robosop
      tier: db
#POD definition
  template:
    metadata: 
      labels:
        component: rabbitmq
        project: robosop
        tier: db
    spec:
      containers: 
      - name: rabbitmq
        image: rabbitmq:3
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    component: rabbitmq
    project: robosop
    tier: db
  ports: 
    - protocol: TCP
      port: 5672 # service port
      targetPort: 5672 # container port
