apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: mongodb
  namespace: roboshop
  # these are replica set labels
  labels:
    component: mongodb
    project: robosop
    tier: db
spec:
  replicas: 1
  selector:
    # these labesl are used to select pods
    matchLabels:
      component: mongodb
      project: robosop
      tier: db
#POD definition
  template:
    metadata: 
      labels:
        component: mongodb
        project: robosop
        tier: db
    spec:
      containers: 
      - name: nginx
        image: navomika18/mongodb:v1
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    component: mongodb
    project: robosop
    tier: db
  ports: 
    - protocol: TCP
      port: 27017 # service port
      targetPort: 27017 # container port
