apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: catalogue
  namespace: roboshop
  # these are replica set labels
  labels:
    component: catalogue
    project: robosop
    tier: backend
spec:
  replicas: 1
  selector:
    # these labesl are used to select pods
    matchLabels:
      component: catalogue
      project: robosop
      tier: backend
#POD definition
  template:
    metadata: 
      labels:
        component: catalogue
        project: robosop
        tier: backend
    spec:
      containers: 
      - name: nginx
        image: navomika18/catalogue:v1
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  selector:
    component: catalogue
    project: robosop
    tier: backend
  ports: 
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port
