apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
data: 
  MONGO: "true"
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/user"
---
apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: user
  namespace: roboshop
  # these are replica set labels
  labels:
    component: user
    project: robosop
    tier: backend
spec:
  replicas: 1
  selector:
    # these labesl are used to select pods
    matchLabels:
      component: user
      project: robosop
      tier: backend
#POD definition
  template:
    metadata: 
      labels:
        component: user
        project: robosop
        tier: backend
    spec:
      containers: 
      - name: nginx
        image: navomika18/user:v1
        imagePullPolicy: "Always"
        envFrom:
        - configMapRef:
            name: user
        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  selector:
    component: user
    project: robosop
    tier: backend
  ports: 
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port
