apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: redis
  namespace: roboshop
  # these are replica set labels
  labels:
    component: redis
    project: robosop
    tier: db
spec:
  replicas: 1
  selector:
    # these labesl are used to select pods
    matchLabels:
      component: redis
      project: robosop
      tier: db
#POD definition
  template:
    metadata: 
      labels:
        component: redis
        project: robosop
        tier: db
    spec:
      containers: 
      - name: redis
        image: redis:7.0
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    component: redis
    project: robosop
    tier: db
  ports: 
    - protocol: TCP
      port: 6379 # service port
      targetPort: 6379 # container port
